# Change these first
owner: caryrx # Your GitHub organization or username, where this repository lives!
repo: Upptime # The name of this repository
retry:
  count: 3
  delay: 10
sites:
  - name: Clair
    url: https://askclair.ai
    icon: https://askclair.ai/favicon-32x32.png
  - name: OnLabel
    url: https://onlabel.ai
    icon: https://onlabel.ai/favicon-32x32.png
  - name: GalenAI
    url: https://prod.askclair.ai/api/v1/helpers/get-hint
  - name: OneDash
    url: https://onedash.cary.health
    icon: https://onedash.cary.health/favicon-32x32.png
  - name: Workbench
    url: https://workbench.caryrx.com
    icon: https://workbench.caryrx.com/logo192.png
    expectedStatusCodes:
      - 403
      - 200
      - 201
  - name: CaryConnect
    url: https://caryconnect.cary.health
    icon: https://caryconnect.cary.health/favicon-32x32.png
  - name: Cary API
    url: https://api5.caryrx.com/v1/zipcodes/20001
  - name: Kinetica
    url: https://prelive.caryrx.com/v1/health/kinetica
    icon: /assets/kinetica.png
  - name: PDFService
    url: https://pdf.caryrx.com/health
    icon: /assets/pdf.png
    headers:
      - "Content-Type: application/json"
      - "lb-token: $PDF_LB_TOKEN"

assignees:
  - bencaryhealth
  - mattcaryrx
skipDeleteIssues: true
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.caryrx.com
  # baseUrl: /Upptime
  logoUrl: https://caryimages.s3.us-east-1.amazonaws.com/caryhealth_logo.png
  name: Status
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
